server:
  port: 8082  # cambia según el servicio (8080, 8081, 8082, etc.)

spring:
  application:
    name: ordenes-service  # un nombre único para cada servicio
  datasource:
    url: jdbc:postgresql://postgres_retry_service_tarea:5432/retry_jobs_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true